JCB Token

JCB Token 是一个基于区块链技术的新型社会实验型代币。

为维护区块链世界公平原旨，JCB Token 不做预挖、没有募资、团队零持币，100%的代币都均将注入 AMM 交易所的资金池。

基本信息
代币名称：JCB Token
代币符号：JCB 
初始总量：10000
代币分配：无预挖、无募资、团队无持币，所有代币投入资金池代币类型：TRC-20
上线交易所：JustSwap
上线时间：2020年 10 月 1日
初始价格：1JCB= 0.1 TRX

合约地址：TKTPDBeTjiyrBmTxrk1rn2awCYw9vMUNVx
